### ISSUE TITLE
Archive this repo and move the data fixture into publishing-api.

### ISSUE THREAD

**Issue by sengi** [alphagov/special-route-publisher#260]
This app's purpose seems to be simply to upsert a set of records from a YAML file to Publishing API. It would seem more natural to put this YAML in alphagov/publishing-api, which is the component responsible for handling these requests anyway, and have it upsert the records on startup.

We want these records to be pushed automatically (ideally on deployment pre-sync) by whichever component is supposed to own the information. I don't think we want this to continue to be a manually-initiated job, since that inevitably leads to production being out of sync with what's in the repo. Not to mention yet another Ruby app to maintain with the dependency-update toil that involves.

**Comment by ChrisBAshton** [comment]
Raised https://trello.com/c/9rOxWNnD/396-retire-special-route-publisher

**Comment by KludgeKML** [comment]
Closing this issue as we're retiring this repo - have done some of it (transferred the rake tasks to publishing-api), the rest is captured in an issue there: https://github.com/alphagov/publishing-api/issues/2888
